- name: Install docker
  hosts: servers
  connection: ssh
  gather_facts: false
  become: no


  tasks:
    - name: Remove docker if installed from CentOS repo
      yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: removed
        use_backend: yum3

   # - name: Install yum utils
   #   yum:
   #     name: yum-utils
   #     state: latest

    #- name: Install device-mapper-persistent-data
    #  yum:
    #    name: device-mapper-persistent-data
    #    state: latest

    #- name: Install lvm2
    #  yum:
    #     name: lvm2
    #     state: latest

    #- name: Add Docker-CE stable repo
    #  yum_repository:
    #   name: docker-ce-stable
    #    description: Docker CE Stable Repo
    #    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    #    gpgkey: https://download.docker.com/linux/centos/gpg
    #    gpgcheck: yes

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes

#    - name: Upgrade Packages
#      yum: name=* state=latest

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Add user vagrant to docker group
      user:
        name: vagrant
        groups: docker
        append: yes
      become: yes
