---

mysql_database: guacamole_db

guacamole_user: guacamole

guacamole_pass: guacamole99

mysql_root_password: guacamole9999

satellite_url: "satellite.paas-govcloud.agilesof.org"
satellite_org_id: "Default_Organization"
satellite_katello_rpm: "http://{{ satellite_url }}/pub/katello-ca-consumer-latest.noarch.rpm"

activation_key: "ak_rhel"